name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Cocoapods to 1.10.0-rc.1
      run: gem install cocoapods --pre
    - name: Install SwiftLint
      run: |
        curl -LO https://github.com/realm/SwiftLint/releases/download/0.39.2/portable_swiftlint.zip
        unzip portable_swiftlint.zip
        mv swiftlint /usr/local/bin
        rm portable_swiftlint.zip LICENSE
    - name: Switch to Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app/Contents/Developer
    - name: Run tests
      run: fastlane scan
      working-directory: SwiftyTesseract
    - name: Lint Podspec    
      run: fastlane lint_podspec tag:3.1.3
      working-directory: SwiftyTesseract
